---
title: "Analisis de Mapas Utilizados en Posters"
author: "Juan Jara"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Librerias:
library(tidyverse)
library(tibble)
library(dplyr)
library(stringr)

#Datos:
datos <- read.csv2("Analisis_Postersv3csv.csv", sep = "\t")

#Funciones 

#Funcion para pasar a frecuencia, los valores absolutos.
pasar_n_a_proporcion <- function(x){ #recibe $n | devuelve vector para colocar en $proporcion
  total <- sum(x)
  i <- 1
  for (variable in x) {
    x[i] <- x[i] / total
    i <- i +1
  }
  return(x)
}


```



<!-- * Análisis de los pósters del CPA -->

<!--   cuántos usaron mapas -->
<!--   de qué tipo cada uno, cuántos basados en OSM -->
<!--   tienen atribución -->
<!--   están disponibles abiertamente. -->


```{r}
#Cuantos Usaron Mapas
#Utilizo un grafico de torta, porque para mi,
#solo tiene utilidad cuando la diferencia es notoria.
cantidad_de_posters_relevados <- 209 
cantidad_de_trabajos_con_mapa <- length(datos$Posee.Mapa)
cantidad_de_trabajos_sin_mapa <- cantidad_de_posters_relevados - cantidad_de_trabajos_con_mapa

posters <- tibble(categoria = c("Con Mapa/s", "No incluyen mapa"),
                  n = c(cantidad_de_trabajos_con_mapa,
                        cantidad_de_trabajos_sin_mapa))

posters$proporcion <- pasar_n_a_proporcion(posters$n)

ggplot(posters, aes(x = "", y = proporcion, fill = categoria))+
  geom_col(color = "black")+
  geom_text(aes(label = categoria), position = position_stack(vjust = 0.5))+
  coord_polar(theta = "y")+
  labs(title  = "Trabajos Relevados")+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#ebf2ff"),
        plot.background = element_rect(fill = "#ebf2ff"),
        legend.position = "none")




```


```{r}
#<!--   de qué tipo cada uno, cuántos basados en OSM -->



```



```{r}

#54 publicaciones con mapas

cantidad_de_mapas <- tibble(mapas = datos$Posee.Mapa) %>%  count(mapas)
cantidad_de_mapas$cantidad <- c(1,2,3,4,5)

cantidad_de_mapas$proporcion <- pasar_n_a_proporcion(cantidad_de_mapas$n)

ggplot(cantidad_de_mapas, aes(x= cantidad, y = proporcion ))+
  geom_bar(stat = "identity")+
  labs(title = "Cantidad de Mapas por publicacion")



```


```{r}
#<!--   de qué tipo cada uno, cuántos basados en OSM -->
#voy a considerar todos los mapas utilizados
nro_de_mapas_total <- tibble( tipo = datos$Posee.Mapa) %>%
  mutate(tipo = tolower(tipo),
         match = str_c("si", collapse = '|'),
         key_word = str_extract_all(tipo, match)) %>%
  select(-match)

nro_de_mapas_total <-  unlist(nro_de_mapas_total$key_word, use.names = FALSE) %>% length()
#93 si, los que poseen doble mapa deberian decir google 2 veces

#view(datos)

google <- tibble( tipo = datos$Tipo.de.mapa.usado) %>%
  mutate(tipo = tolower(tipo),
         match = str_c("google", collapse = '|'),
         key_word = str_extract_all(tipo, match)) %>%
  select(-match)

osm <- tibble(tipo = datos$Tipo.de.mapa.usado) %>% 
  mutate(tipo = tolower(tipo),
         match = str_c("openstreetmap", collapse = '|'),
         key_word = str_extract_all(tipo, match)) %>%
  select(-match)

svg <- tibble(tipo = datos$Tipo.de.mapa.usado) %>% 
  mutate(tipo = tolower(tipo),
         match = str_c("svg", collapse = '|'),
         key_word = str_extract_all(tipo, match)) %>%
  select(-match)


google <-  unlist(google$key_word, use.names = FALSE) %>% length()
osm <-  unlist(osm$key_word, use.names = FALSE) %>% length()
svg <- unlist(svg$key_word, use.names = FALSE) %>% length()

otros <- nro_de_mapas_total - google - osm - svg

servicios <- tibble(categoria = c("Servicios de Google",
                                  "OpenStreetMap" ,
                                  "Svg sin fuente",
                                  "Otros"),
                n = c(google,osm,svg,otros ))


servicios$proporcion <- pasar_n_a_proporcion(servicios$n)

ggplot(servicios, aes(x = "", y = proporcion, fill = categoria))+
  geom_col(color = "black")+
  geom_text(aes(label = categoria), position = position_stack(vjust = 0.5))+
  coord_polar(theta = "y")+
  labs(title  = "Servicios Utilizados")+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#ebf2ff"),
        plot.background = element_rect(fill = "#ebf2ff"),
        legend.position = "none")


```


```{r}
#<!--   tienen atribución -->
#voy a considerar todos los mapas utilizados
con_atribucion <- tibble( tipo = datos$El.mapa.tiene.atribucion) %>%
  mutate(tipo = tolower(tipo),
         match = str_c("si", collapse = '|'),
         key_word = str_extract_all(tipo, match)) %>%
  select(-match)

con_atribucion <-  unlist(con_atribucion$key_word, use.names = FALSE) %>% length()
#21 si

#view(datos)

sin_atribucion <- tibble( tipo = datos$El.mapa.tiene.atribucion) %>%
  mutate(tipo = tolower(tipo),
         match = str_c("no", collapse = '|'),
         key_word = str_extract_all(tipo, match)) %>%
  select(-match)

sin_atribucion <- unlist(sin_atribucion$key_word, use.names = FALSE) %>% length()
#68 no



atribucion <- tibble(categoria = c("Con atribucion",
                                  "Sin atribucion"),
                n = c(con_atribucion, sin_atribucion ))


atribucion$proporcion <- pasar_n_a_proporcion(atribucion$n)

ggplot(atribucion, aes(x = "", y = proporcion, fill = categoria))+
  geom_col(color = "black")+
  geom_text(aes(label = categoria), position = position_stack(vjust = 0.5))+
  coord_polar(theta = "y")+
  labs(title  = "De los que utilizaron un mapa..")+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        panel.background = element_rect(fill = "#ebf2ff"),
        plot.background = element_rect(fill = "#ebf2ff"),
        legend.position = "none")


```
